<?php

namespace Tests\Feature;

use Tests\TestCase;
//use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
//use Illuminate\Foundation\Testing\DatabaseTransactions;

class ReadThreadsTest extends TestCase
{
    use DatabaseMigrations;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }

    public function test_a_user_can_browse_all_threads()
    {

        $response = $this->get('/threads');

        $response->assertSee($this->thread->title);


    }

    public function test_a_user_can_browse_single_thread()
    {

        $response = $this->get('/threads/'.$this->thread->id);

        $response->assertSee($this->thread->title);
    }

    public function test_a_user_can_replies_that_are_associated_with_a_thread(){
        $reply = factory('App\Reply')->create(['thread_id' => $this->thread->id]);

         $this->get('/threads/'.$this->thread->id)
         ->assertSee($reply->body);
    }
}
